// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-2:373510c9-f52a-4d5f-886b-37870783e04b',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'amplifytestapp-hosting-mobilehub-849898523',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3op1juyqmkvaa.cloudfront.net',
    'aws_mobile_analytics_app_id': '6a0fba50fb6c4954848b2236c1010941',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'fff8ac24-9af7-467c-bdd9-318e4bfc485b',
    'aws_project_name': 'AmplifyTestApp-2018-06-25-11-25-11',
    'aws_project_region': 'eu-west-2',
    'aws_resource_name_prefix': 'amplifytestapp-mobilehub-849898523',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'eu-west-2_1CSmdMXsF',
    'aws_user_pools_web_client_id': '10i22egikkmdnutunr2jbk81uo',
}

export default awsmobile;
