// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-west-2:d4e7192e-5f9f-477a-af32-38c056b7633f',
    'aws_cognito_region': 'eu-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsamplifylearningpr-hosting-mobilehub-1885972200',
    'aws_content_delivery_bucket_region': 'eu-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd31yfm2w11pk9u.cloudfront.net',
    'aws_mobile_analytics_app_id': '9c1f13d8d1a348d9a717cce94e786df1',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '2e00e43d-1e18-41ef-bfc6-277de3548794',
    'aws_project_name': 'AwsAmplifyLearningProject',
    'aws_project_region': 'eu-west-2',
    'aws_resource_name_prefix': 'awsamplifylearningpr-mobilehub-1885972200',
}

export default awsmobile;
